trainingInput:
  ## BASIC_GPU uses single NVIDIA Tesla K80 GPU.
  pythonVersion: '3.5'
  scaleTier: BASIC_GPU
  ## Custom scaleTier needed for using > 1 GPU machines.
  # scaleTier: CUSTOM
  # masterType: complex_model_m_gpu
  # workerType: complex_model_m_gpu
  # parameterServerType: large_model
  # workerCount: 9
  # parameterServerCount: 3
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: val_auc_roc
    maxTrials: 10
    maxParallelTrials: 3
    enableTrialEarlyStopping: TRUE
    params:
      - parameterName: learning_rate
        type: DOUBLE
        minValue: 0.00005
        maxValue: 0.1
        scaleType: UNIT_LOG_SCALE
      - parameterName: dropout_rate
        type: DOUBLE
        minValue: 0
        maxValue: 1
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: batch_size
        type: DISCRETE
        discreteValues:
        - 64
        - 128
        - 256
